name: flutter_task_planner_app

description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^2.1.3
  google_maps_flutter: ^2.0.11
  simple_animations: ^4.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^1.1.0
  flutter_svg: ^0.19.3
  eva_icons_flutter: ^3.0.2
  get: ^4.3.8
  bordered_text: ^2.0.0
  flutter_signin_button: ^2.0.0
  intl: ^0.17.0
  timeago: ^3.1.0
  flutter_week_view: ^1.2.0
  sqflite: ^2.0.0+4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
